name: "Test: Fetch"
on:
  push:
    paths:
      - 'test/fetch/**'
jobs:
  Run-Regular-Fetch-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Test Fetch JS
        run: |
          cd test/fetch
          echo "--[ FETCH ]------------------------"
          node fetch.js

          success="$(node fetch.js | tail -n 1)"
          if echo "$success" | grep -q "SUCCESSFUL: Yes"; then
            echo " " # placeholder idk
          else
            echo "--[ RESULTS ]------------------------"
            echo "Fetch error."
            exit 1
          fi

          
          echo "--[ RESULTS ]------------------------"
          echo "Successful fetch!"
          exit 0
  Run-Fetcher-Service-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Test Fetcher Service JS
        run: |
          cd test/fetch
          echo "--[ FETCH ]------------------------"
          node cable.mjs

          success="$(node cable.mjs | tail -n 1)"
          if echo "$success" | grep -q "SUCCESSFUL: Yes"; then
            echo " " # placeholder idk
          else
            echo "--[ RESULTS ]------------------------"
            echo "Fetch error."
            exit 1
          fi

          
          echo "--[ RESULTS ]------------------------"
          echo "Successful fetch!"
          exit 0
          
